version: "3.9"
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/students


  service-db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "students"
      POSTGRES_USER: "postgre"
      POSTGRES_PASSWORD: "1234"

    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  db-data: